// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteFeedList(arg1:backend.FeedsInfo):Promise<void>;

export function GetFeedContent():Promise<Array<backend.FeedContentsInfo>>;

export function GetFeedList():Promise<Array<backend.FeedsInfo>>;

export function GetHistory():Promise<Array<backend.FeedContentsInfo>>;

export function InitDatabase():Promise<void>;

export function SetFeedList(arg1:Array<backend.FeedsInfo>):Promise<void>;

export function SetHistory(arg1:Array<backend.FeedContentsInfo>):Promise<void>;

export function SetHistoryReaded(arg1:backend.FeedContentsInfo):Promise<void>;
